# modified from https://github.com/haojiwu/line-bot-python-on-render/blob/master/render.yaml
services:
- type: web
  name: samtsai-line-bot-python-flask
  env: python
  repo: https://github.com/LiyangTseng/Leftover-Notifier
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn main:app
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
    
- type: web
  name: clock
  start_command: python clock.py
